cwacek/python-jsonschema-objects

.gitignore, python_jsonschema_objects/classbuilder.py
Pretty simple, but the jsonschema spec says that 'numbers' are any valid integer/float/long/double/whatever. 
Also I had to add in some compatibility fixes for Python3. All tests pass.
=> Add in support for long (instead of just int/float), and add a .gitignore.

python_jsonschema_objects/classbuilder.py
Hi!
I'd like to propose a little patch to improve a bit error message for missing attributes, so ugly
> ValidationError: '['id', 'type']' are required attributes for \<class 'abc.resource'>
becomes neat
> ValidationError: '['id', 'type']' are required attributes for resource
=> Improve error message for missing required attributes

python_jsonschema_objects/validators.py
I fixed the behavior of python_jsonschema_objects for the "exclusiveMinimum" and "exclusiveMaximum" jsonschema properties so they behave per the jsonschema draft4 spec. I also made all the validator error messages consistently present tense.
=> fixed behavior of python_jsonschema_objects for "exclusiveMinimum" and "exclusiveMaximum" jsonschema properties

python_jsonschema_objects/classbuilder.py
There are few places in classbuilder whcih logging is used
instead of logger.
The side effect of using the logging was that the user of this library
could not enitely mask the debug logs of python_jsonschema
with this change the user can now set the logging level for this
library by calling setLevel
=> use logger instead of logging in the class_builder

README.md, python_jsonschema_objects/classbuilder.py, test/test.py
There was an issue in the as_dict method of protocol base
where it wasn't ever explicitly checking for subclasses
of ProtocolBase and calling as_dict for them. This makes
the check explicity, rather than implicit (by checking for other
conditions or the existence of 'as_dict')
=> bugfix: Fixes #35 and adds a test case

python_jsonschema_objects/classbuilder.py
When array items are references to another schema, we must allow for the
possibility that we need to resolve additional references for an `allOf`
definition. As such, we call `construct()` rather than
`_build_object()`.
This is a fix for #39.
=> Construct array item references.

python_jsonschema_objects/classbuilder.py, test/test_regression_8.py, tox.ini
Literal comparators were failing because they were using __cmp__, so this switches them to use __eq__, __hash__ and __lt__. It also adds a test for the functionality.
=> Fix #8. Python 3 removes support for __cmp__.

python_jsonschema_objects/classbuilder.py, test/test_regression_17.py
This fixes #17 by allowing an array to be passed for 'type'. The provided value will be validated as *one* of the provided types, just like the spec says.
=> feature: Permit an array to be provided for 'type'. Fixes #17

python_jsonschema_objects/validators.py
The `long` type is a valid Python numeric type. Allow it when checking
`number` types.
=> Allow long number type.

python_jsonschema_objects/classbuilder.py
Use `getattr(self.__class__, property_name)` to get properties and set
them. This is compatible with using a class builder as a base class. In
my case, I'm extending class builders so that I can add constants for
enum values directly to the class definition rather than having to use
strings.
=> Make property setting robust to inheritance.

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/pattern_properties.py, python_jsonschema_objects/validators.py, test/test_pattern_properties.py
This adds support for patternProperties by replacing the
multi-valued __extensible__ flag with a new ExtensibleValidator class
that handles all "extensibility" functionality, including
additionalProperties and patternProperties.
This also adds a bunch of tests to validate this functionality
(and that the resolution order is correct).
Fixes #44
=> feature: Adds support for patternProperties

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/pattern_properties.py, python_jsonschema_objects/validators.py, test/test_pytest.py
Type checking has precedence since `isinstance(True, int) == True` in
Python. Convert schema mappings to sequence of tuples instead of `dict`
to maintain precedence during type checking.
=> Support boolean in schema child object.

python_jsonschema_objects/__init__.py, test/test_pytest.py, test/test_regression_17.py
If the schema isn't valid, the error messages from this library are inscrutable.
Solution: check the schema before trying to load it
=> feature: Use jsonschema to validate the schema itself before load

python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, test/test_pytest.py
The classbuilder works on the schema object, and ends up changing values
in it as types are discovered and resolved. This causes problems when
calling build_classes more than once. This change makes it so the
builder always uses a copy of the schema when calling build_classes()
=> bugfix: Resolve the correct reference type for objects

python_jsonschema_objects/classbuilder.py
Update ProtocolBase.__eq__ to check if the other thing is a ProtocolBase first. Fixes #72
=> Update __eq__ to check class type first.

requirements.txt
This fixes the incompatibility issue with [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) and closes https://github.com/cwacek/python-jsonschema-objects/issues/81.
=> bugfix: Update requirements

python_jsonschema_objects/classbuilder.py
There is a duplicate __str__ definition in classbuilder.
@cwacek
=> Remove duplicate __str__ definition

python_jsonschema_objects/classbuilder.py, test/test_pytest.py
Literal types (string, number, boolean, etc) will now support default
values when instantiated.
Making this work required keeping track of subproperties with default
values in the object class, because there's no way to retrieve the
property descriptor without instantiating it at runtime.
Fixes #80
=> feature: Permit the use of default values for literals.

.codeclimate.yml, .travis.yml, conftest.py, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/examples/README.md, python_jsonschema_objects/literals.py, python_jsonschema_objects/pattern_properties.py, python_jsonschema_objects/util.py, test/test_regression_8.py, tox.ini
Fixes an issue introduced in 3.0.0 where Literals could no longer be directly operated on because they were always wrapped in a class. the LiteralValue class now dispatches the vast majority of operators through to the underlying value.
In addition, added support for doctests based on the README file, so the examples in the README actually get executed as tests! These tests can reference the schemas written into the README file too - INCEPTION! This actually caught a few examples that were wrong. 
Fixes #96
=> Bugfix: Dispatch literal operators to literal values

python_jsonschema_objects/classbuilder.py, test/test_regression_89.py
Fixed a bug where a StopIteration exception would be raised because of
improper filtering on the `validators.SCHEMA_TYPE_MAPPING` when
searching for a property's type definition.
Added a regression test for the bug. The test uses a schema where a property's `type` was defined in a `oneOf`.
This hits the code path of the bug.
=> Fix property setting bug when typ is dict

python_jsonschema_objects/classbuilder.py, test/test_regression_90.py
This commit attempts to permit missing parameters if their type could be
the `null` type.
Currently null types are not supported 100% in
python_jsonschema_objects.
Assuming a schema where the type of a variable `foo` is `null`, and
where strict enforcing was used for schema validation:
* `Object(foo=None)` should be valid as is valid as of this commit
* `Object()` should *NOT* be valid but it is valid as of this commit. There might not be a way to get around this.
=> Make a patch to better support null types.

python_jsonschema_objects/classbuilder.py
This PR provides a fix for initializing properties that have defined default values.  An existing issue arises when None is used; and the default values are of an "enum" types that requires the default value.
=> fix issue-27: properties that have defaults are initiatized with defaults

python_jsonschema_objects/classbuilder.py, test/test_regression_114.py
Since we are looking for 'items' in the code, which should look like so:
[{u'type': u'string'}, {u'type': u'int'}]
passing the array does not have get method which is called in the construct() since it's not a dictionary, whereas the element of the array will.
=> Fix where the whole array was passed instead of the element

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/wrapper_types.py
Reimplemented circular $ref handling so that referenced schemas could be used anywhere, including array items validators.
Previously, this was possible:
{
"id": "mySchema",
"type": "object",
"properties": {
"data": {
"type": "object"
},
"child1": {
"$ref": "mySchema"
},
"child2": {
"$ref": "mySchema"
}
}
}
while this was not:
{
"id": "mySchema",
"type": "object",
"properties": {
"data": {
"type": "object"
},
"children": {
"type": "array",
"items": {
"$ref": "mySchema"
}
}
}
}
Also fixed a minor bug in construction of array validator with a list of schemas for items.
Also added support for required properties of nullable types (as opposed to the single null type):
{
"id": "mySchema",
"type": "object",
"properties": {
"data": {
"type": [
"object",
"null"
]
}
},
"required": [
"data"
]
}
=> Better support for circular references

python_jsonschema_objects/classbuilder.py, test/test_wrong_exception_protocolbase_getattr.py, test/test_wrong_exception_protocolbase_getitem.py
To declare a dict like object in json-schema, we are supposed to declare it as an object of additional properties. When trying to use it as dict, for instance testing if a key is inside the dictionary, methods like __contains__ in the ProtocolBase expect __getitem__ to raise a KeyError. 
__getitem__ was calling __getattr__ without any exception handling, which raises an AttributeError (necessary for proper behaviour of getattr, for instance).
Solution found is to handle AttributeError in getitem and to raise KeyError
=> Fix wrong exception raised in ProtocolBase getitem

python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/examples/README.md, setup.cfg
This adds a couple of options to `build_classes` to work around the issue described in #141, where unexpected fields appeared in the namespace. The main addition is `named_only`, which will restrict the set of objects that appear in the namespace to the top level object, and anything which has a `title` attribute. 
The README has been updated to reflect this and test the behavior. I also slightly re-ordered the README.
=> Fix #141 by adding an option to only keep titled elements

requirements.txt
I dont see this imported anywhere within the project, and doesnt (appear) to be used in any fashion. If it is, please let me know!
Otherwise, removing this is just a wee bit of tech debt cleanup
=> Removing old pandocfilters requirement

development.txt, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/descriptors.py, python_jsonschema_objects/wrapper_types.py, test/test_regression_143.py, tox.ini
Fixes #143 by checking dirty flags for arrays and properties before revalidating. In order to allow for strict mode, this also passes the 'strict' flag down to the Array validator, in which case it will revalidate on every change.
=> Feature: Don't revalidate arrays on every change by default

setup.py, tox.ini
Tests pass in py35, py36, and py37 without any issue.
I also updated the `classifiers` to reflect py36 and py37 support.
=> Test in python3.7 as well

python_jsonschema_objects/__init__.py, test/test_pytest.py, test/test_regression_17.py
The "$id" keyword defines a URI for the schema.
[8.2. The "$id" Keyword](https://json-schema.org/latest/json-schema-core.html#id-keyword)
=> The $id Keyword

requirements.txt, setup.py, tox.ini
I was interested in fixing #154, so I started looking into whether we'd need to make major changes to this library to support `jsonschema` 3.0. But it looks like it works just fine!
I modified the `setup.py` pin on `jsonschema` from `~=2.3` to `>=2.3`, and then updated the `tox.ini` to test against all the current minor versions of `jsonschema>=2.3`. 
Since the combination of `setup.py` and tox handle all the version pinning, `requirements.txt` is no longer necessary, so I deleted that and removed the code in `setup.py` that parsed it.
=> Test against jsonschema versions 2.3, 2.4, 2.5, 2.6, 3.0

conftest.py, python_jsonschema_objects/markdown_support.py, setup.py, tox.ini
This is similar to the loosening of the pin on `jsonschema`, but for `inflection` and `Markdown`. This is mainly so that future version bumps of those dependencies don't cause version conflicts later on down the road.
I figured we don't care as much about the minor versions of `Markdown` so I only tested against 2.* and 3.*.
`inflection` hasn't been updated in 4 years so I didn't have another major version to test against.
I replaced the tabs in `markdown_examples` with spaces to be consistent with the rest of the file.
=> Loosen `inflection` and `Markdown` pins, and support `Markdown` 3.*

.travis.yml
I forgot to make Travis test against python3.7 in #157 (whoops).
I had to update the distribution to xenial because the default (trusty) doesn't support python3.7.
=> Test against python3.7 in Travis

python_jsonschema_objects/wrapper_types.py
Originally, "uniqueItems" was detected like this:
`if getattr(self, 'uniqueItems', None) is not None:`
However, this means that the attribute must simply be set, regardless of true/false. Therefore, if you set `"uniqueItems" : false` it would still test for uniqueness.
=> Made uniqueItems explicitly look for TRUE and not any value

python_jsonschema_objects/classbuilder.py, test/test_regression_156.py
This was a silly bug. Didn't explicitly call validate when resolving types in __new__.
Fixes #156
=> bugfix: Fix #156.

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/descriptors.py, test/test_regression_156.py, test/test_regression_165.py
This resolves a couple of issues related to attribute deletion.
First, all the various del methods now work, including those that use
attribute syntax such as `del foo.bar`.
Second, the handling of attribute deletion works properly for
additionalProperties and standard properties in that for
additionalProperties, the property is just removed, but for standard
properties it is set to None. Standard properties that are `required`
are not permitted to be deleted.
=> bugfix: Properly handle attribute deletion. Fixes #165

python_jsonschema_objects/classbuilder.py, test/test_regression_165.py
As pointed out in #172, we need to use the object.__delattr__
function under certain conditions. There was no test for the case
where we deleted a property that didn't exist, and that was the one bad
case. This resolves that.
=> bugfix: Properly use baseclass delattr. Fixes #172

python_jsonschema_objects/__init__.py, python_jsonschema_objects/examples/README.md, test/test_pytest.py
Additionally, this will cause the library to "warn" if the `$schema`
requested isn't known.
Fixes #174
=> feature: Add more substantive indications about what is/isn't supported

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/pattern_properties.py, python_jsonschema_objects/wrapper_types.py, test/test_feature_151.py, test/test_pytest.py, test/test_regression_156.py
This resolves an issue where if a oneOf was hidden behind a $ref
at the toplevel of an schema (I know), then it would fail to load properly.
It turns out this is just because the top level reference was using an
old method for resolving  type proxies. Updating it to use the TypeProxy
object resolved the issue.
Some minor refactoring of names too.
=> Feature: Fixes #151

python_jsonschema_objects/__init__.py, test/test_pytest.py
Fix supported versions list correspond to https://json-schema.org/understanding-json-schema/reference/schema.html#the-schema-keyword
This fix removes useless warning.
Remove unused regex module import.
Reformat imports in __init__.py file correspond to PEP8.
=> fix_supported_schema_versions

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/util.py, python_jsonschema_objects/wrapper_types.py
The current warnings emitted:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
=> fixing Python 3.8 ABC deprecation

python_jsonschema_objects/literals.py, test/test_regression_213.py
Account for whether or not our comparator is a Literal itself.
Additionally use functools.total_ordering to make sure all
comparisons work.
=> Fix #213: Properly support total ordering for literals

python_jsonschema_objects/markdown_support.py
`markdown.version_info` was removed in Markdown 3.4
=> Handle removed markdown version_info

.github/workflows/pythonpackage.yml, .pre-commit-config.yaml, python_jsonschema_objects/descriptors.py, python_jsonschema_objects/markdown_support.py, python_jsonschema_objects/pattern_properties.py, test/test_nested_arrays.py, test/test_regression_232.py, tox.ini
Allows a nested `oneOf` to refer to other schema types than `object` by considering the keyword expansion when needed.
- fixes #232
- fix `markdown` package that uses `__version_info__` in more recent versions instead of `version_info`
(duplicate functionality as https://github.com/cwacek/python-jsonschema-objects/pull/230)
- fix broken test that assumed default schema `draft-04` not supported by new default in `jsonschema`
=> fix nested oneOf resolution with different schema types (fixes #232)

setup.py
Closes #237
This fixes the upper bound for the jsonschema dependency, so any version below 4.18 is allowed.
As a matter of style, I was unsure if I should specify the upper bound as 4.18 or 4.18.0, but the lower bound is specified in major.minor style, so I went with 4.18.
=> bugfix: Pin jsonschema below 4.18 (not 4.1.8)

python_jsonschema_objects/classbuilder.py, test/test_regression_217.py
This partially fixes #217 by appropriately handling defaults when
they're references to literals. However, it's still not working
for objects because the object is prepared to have default
properties, but not to have a default for the object in
general.
=> WIP: Resolve defaults through reffs

tox.ini
Currently, CI runs tests on Python 3.7-3.11, but `tox.ini` still lists the older range 3.6-3.8.
That affects local development, because running `tox` does not test with 3.9, 3.10, or 3.11, even when those Python versions are installed on the local development system. (I noticed this when locally testing #238.) Less importantly, it is probably not necessary to test on Python 3.6 anymore, because it has been unsupported for a long time.
This PR changes the Python version range in `tox.ini` to match the range tested on CI (in the `build` step in `pythonpackage.yml`).
Although Python 3.7 is [recently unsupported](https://devguide.python.org/versions/) as well, I have not removed it in this PR. If 3.7 is to be removed from `tox.ini`, then that should also be done in `pythonpackage.yml`, and it …
=> tests: Update tox.ini versions list to match CI

setup.py
This updates the classifiers listed in `setup.py`.
Removals:
- **Python 2 classifiers.** Although a significant amount of the code remains written in the common subset of Python 2 and Python 3, the codebase overall no longer supports Python 2. For example, `collections.abc` is imported.
- **Python 3.5.** Not all tests reliably pass. Specifically, `test_regression_208` sometimes passes and sometimes raises `TypeError`. Later versions do not show such nondeterministic behavior, even when the test is run many times in succession (it always passes).
- **Python 3.6.** Tests still pass. This version does appear still to work. However, 3.6 has been unsupported by the PSF for a significant time, and it is no longer tested in `tox.ini` or in the CI test workflow.
Additions: **3.8**, **3.9**, …
=> build: Update classifiers stating Python versions

.gitignore, development.txt
This updates the "development requirements" file development.txt to remove some packages that are no longer in use and add some that were not listed but are in use. This file, which is not being used on CI but is helpful in local development, is updated as follows:
- Remove nose and rednose, which are long-unused. nosetests is not currently being used on this project, which was migrated to pytest some time ago, and it also doesn't support Python 3.10+.
- Add coverage, which is used heavily, and already listed as a dependency (and used) in tox.ini.
- Add black, which is used as a linter on CI, to make local linting and fixing easier. Although black is given with an exact version on CI, I have omitted the version number here, since one benefit of having black in development.txt is to test …
=> cleanup: Update tools listed in development.txt

.github/workflows/pythonpackage.yml, .pre-commit-config.yaml
This updates black and improves the command used to run it.
- Update repo URL from `ambv/black` to `psf/black` in pre-commit hook
- Update black version from 23.3.0 to 23.7.0 in pre-commit hook
- Update black version (same as above) in the linting job
- Make command simpler and more robust, using `--extend-exclude`
The change to the command is probably the most significant of these changes. The main reason the command is now more robust is that it was previously using `$()` command substitution in a way that would do the wrong thing on filenames that contain whitespace or special characters like `*` (though there is also the issue that grep would match `.py` anywhere in filenames rather than just at the end). This repository doesn't contain any files with such names, but even if such …
=> workflows: Update black and improve command

tox.ini
This simplifies the test command in `tox.ini` by:
- Using `coverage` directly (`python -m` no longer needed on any platforms)
- Using `pytest` instead of the very old `py.test` command
It also improves stylistic consistency in `tox.ini`, mostly in how whitespace is used. I've tried to put everything in the style that appears most preferred based on what is already there.
I had originally made these changes (locally) as part of a larger change that added experimental Python 3.12 support. But I realized that this cleanup is conceptually separate, should probably be reviewed separately, and seems to be of value whether or not the addition of experimental 3.12 testing is added afterwards. So I've opened this PR for just the cleanup.
=> cleanup: Simplify test commands, harmonize style

.github/workflows/publish.yml, .github/workflows/pythonpackage.yml
This updates versions of GitHub Actions, *except* in the `stale.yml` workflow. The upgraded actions in other workflows are `checkout`, `setup-python`, and `gh-action-pypi-publish`.
The checkout and setup-python actions were upgraded across major versions. Although it is possible for major version updates to introduce incompatibilities, I believe the advantages decisively outweigh the disadvantages, because:
- The syntax the workflows are using remains supported.
- They were upgraded in some places already, just not all.
- As noted in warning annotations shown on this project's [workflow runs](https://github.com/cwacek/python-jsonschema-objects/actions/runs/5803097120), old Node 12 actions [may break around 27 September](https://github.blog/changelog/2022-09-22-github-actions-all-actions-wi …
=> workflows: Update CI action versions

test/test_regression_143.py
In both `test_regression_143` tests, mocks for `validator.validate` were created and bound to `validate` variables, but no assertions were made using them. The `validate` variables were like the `validate_items` variables, but for `validator.validate` instead of `validator.validate_items`, and unused, with no observable effects.
It is possible to add assertions for `validate.call_count`, alongside the existing `validate_items.call_count` assertions. I did this first, asserting the same number of call counts as in the corresponding `validate_items` assertions. If this is what is intended, then that could be kept, and the second commit in this PR dropped or reverted.
However, considering the effect of that change together with the code introduced in #149 (which completed #143) suggests …
=> cleanup: Remove unused test_regression_143 "validate" mocks

.github/workflows/pythonpackage.yml, tox.ini
Closes #250
This makes two related changes:
- **Fixes the `coverage` command** in `tox.ini` so it works on Windows (#250), by using `coverage run -m pytest`, which is the approach to running `pytest` that `coverage` currently shows [in its documentation](https://coverage.readthedocs.io/en/7.3.0/#quick-start).
- **Expands the CI test matrix** to test on Ubuntu, macOS, and Windows, for a total of 15 CI test jobs (5 Python versions, 3 operating systems).
This makes testing on CI more robust. Even when not deliberately relying on any platform-dependent features, it is possible to have a bug that only causes a test to error out or fail on some operating systems and not others. (Testing multiple OSes on CI may also be seen as regression testing for #250, but I think that is actually a less …
=> tests: Test on multiple operating systems

.github/dependabot.yml
This enables [Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) for GitHub Actions. Considerations:
- This would automate pull requests along the lines of #246, but separate PRs for each dependency.
- [Grouped version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) *could* be set up. The feature is [now considered stable](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/). But GitHub Actions don't tend to be updated often enough that I would expect a benefit from this.
- The main goal of enabling Dependabot version updates is not security. If …
=> tools: Enable Dependabot version updates for GitHub Actions

.pre-commit-config.yaml
This builds on the changes in #245, taking care of some things I had missed:
- **Change repo from [psf/black](https://github.com/psf/black) to [psf/black-pre-commit-mirror](https://github.com/psf/black-pre-commit-mirror)**, for speed, as [the `black` documentation has been updated to recommend](https://github.com/psf/black/blob/main/docs/integrations/source_version_control.md). I had previously changed it from [ambv/black](https://github.com/ambv/black) to [psf/black](https://github.com/psf/black), since [ambv/black](https://github.com/ambv/black) redirects to [psf/black](https://github.com/psf/black), and because [psf/black](https://github.com/psf/black) is shown in [the stable docs](https://black.readthedocs.io/en/stable/integrations/source_version_control.html). However, [the latest …
=> tools: Update pre-commit configuration for black

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/util.py, test/test_regression_218.py
+ There were two sets of similar JSON serialization logic in place. This unifies them by just making all our custom objects call for_json() which already does the right thing.
+ The actual bug is fixed by permitting None values to serialize to JSON, iff the type of the object is "null"
Aside: I still don't understand why objects with _type_ null exist
in the JSONSchema spec, but w/e.
=> bugfix: Fix #218 by serializing "null" for "null" types

.github/workflows/pythonpackage.yml, python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/examples/README.md, setup.py, test/test_nondefault_resolver_validator.py, test/test_pytest.py, test/test_regression_232.py, test/thing-one.json, test/thing-two.json, tox.ini
This adds support for jsonschema >4.18, but breaks support below that because of the breaking changes in that library.
=> Migrate to jsonschema 4.18

python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, test/test_feature_51.py
=> Setup for handling anyOf simplifying to oneOf on import.

python_jsonschema_objects/classbuilder.py, test/test_feature_51.py
Added a test, but more could be good or a review of the edge cases given the changes to classbuilder.py
=> #51 handle nested anyof, ensure that data gets passed down via object creators

python_jsonschema_objects/classbuilder.py
Consider the following json schema snippet to define a property:
```json
{
"type" : "number",
"minimum" : 0,
"maximum" : 1,
"default": 0
}
```
The code that sets the default reads:
```python
"__default__": clsdata.get("default") or clsdata.get("const"),
```
If the default is `0` as in the example above, then the right branch of the `or` will be selected and result to None.
=> Fix 0 default values appearing as None

conftest.py, python_jsonschema_objects/classbuilder.py, test/test_292.py
The fix ended up being essentially what was described in #292, but added a bunch more tests to check a few cases. The root cause was that once B had resolved a reference to A, then any references inside A were resolved in relation to B instead of A.
Fixes #292
=> Fix 292 by adding intermediary class builder.

python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, test/resources/adaptive-card.json, test/test_297.py
This PR fixes #297, which was a real issue. Unfortunately it also highlighted that the desired use case won't work because the adaptivecard schema appears to be invalid?
If I can't get to an explanation on how the schema _should_ work, will mark the failing test as xfail and merge this.
=> Attempt to resolve #297
