python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/validators.py
Minor fixes for array validation and circular references in Schema definition
=> Minor fixes for array validation and circular references in Schema definition

python_jsonschema_objects/__init__.py, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/util.py, python_jsonschema_objects/validators.py, test/test.py, tox.ini
I used six to make it work with python 3. I tested on 3.4 only.
=> make python3 compatible

python_jsonschema_objects/classbuilder.py
Depending on the schema version, type can be an array or a dictionary. This should handle both and allow for proper type comparisons with the new schema version. 
I also changed getattr to hasattr, since the latter won't throw a ValueError if it's attribute isn't found (which I believe was the intended check). 
Sorry about the soft quotes -> hard quotes too, I can update my PR if you want.
Maybe related to #9? I doubt it though, since they're using the old schema. /me shurgs.
=> A fix for OneOf handling

python_jsonschema_objects/classbuilder.py
I was running into issues with a 'null' field. This resolves it!
=> Fix handling of Null fields

.travis.yml, python_jsonschema_objects/validators.py
Fixes #25 by correcting the typoed variable name.
=> Fix incorrect parameter

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/validators.py, test/test_regression_49.py
Also make top-level array types expose the same interface as
ProtocolBase (from_json, serialize).
Fixes #49
=> bugfix: Support oneOf in array types.

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/util.py, python_jsonschema_objects/validators.py, test/test_nested_arrays.py
Most of these cropped up with nested array objects
+ bugfix: Permit typeinfo to be ArrayValidator (if we've already seen the type).
+ bugfix: Actually serialize ArrayValidators properly.
+ bugfix: Don't drop basic array items when performing validation
+ tests: Add test for nested arrays.
=> Fixes several issues handling arrays

python_jsonschema_objects/__init__.py
=> Fixes UnicodeDecodeError on Windows with national preferred encoding

.travis.yml, setup.py, tox.ini
Change version specifiers to 'compatible' version. Fixes #69
=> Shift tests to use setup install_requires.

python_jsonschema_objects/examples/README.md, test/test_pytest.py, test/test_regression_87.py
Fixes #87. This really just adds a section to the README and a test
to validate that I'm not just spouting nonsense ;)
=> feature: Explain how to build multiple top level objects.

.travis.yml, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/examples/README.md, tox.ini
Writing actual examples into the README flushes out some issues. In this
case I fixed an issue with  resolution at the top level.
Fixes #85
=> Significantly improved documentation and some new tests.

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/examples/README.md, test/test_circular_references.py
Adds support for circular references, so classes can now refer to eachother.
Builds mostly upon the work of @omerbn in #97, but adds some tests, documentation and refactors a little bit.
=> Feature: support circular references

python_jsonschema_objects/classbuilder.py
Instead of re-creating classes each time we encounter them, we use the already created classes
=> Feature/caching: reusing already created classes

python_jsonschema_objects/examples/README.md
=> Possible typo in the README

python_jsonschema_objects/wrapper_types.py
fix message in maxItems validation error messages
=> typo in error messages

.travis.yml, python_jsonschema_objects/classbuilder.py, test/test_regression_133.py, tox.ini
=> bugfix: Copy default arguments to avoid the typical default issue

requirements.txt, setup.py
=> versioning: Allow any 2.x version of Markdown

python_jsonschema_objects/examples/README.md
=> Add a "Reviewed by Hound" badge

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/wrapper_types.py, test/test_regression_126.py
=> bugfix: Add a `__hash__` implementation to ProtocolBase

python_jsonschema_objects/examples/README.md
=> Noted JSON Schema draft support

python_jsonschema_objects/classbuilder.py, test/test_feature_177.py, test/test_pytest.py
=> feature: Support pjo literals as attribute keys.

python_jsonschema_objects/wrapper_types.py
=> Fix 188: Check for ArrayWrapper, then collections.Sequence

.github/workflows/pythonpackage.yml, .pre-commit-config.yaml, python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/descriptors.py, python_jsonschema_objects/literals.py, python_jsonschema_objects/wrapper_types.py, test/test_pattern_properties.py, test/test_pytest.py, test/test_regression_208.py
This fixes #208 by making sure that we check that instantiated classes are _valid_ before we finish checking oneOf types.
=> Fix #208 by validating in the right place

python_jsonschema_objects/wrapper_types.py
This just applies the fix from #207 in a way I can actually merge it.
=> Apply #207

python_jsonschema_objects/__init__.py
This mirrors #204 with changes to linting applied. Necessary because I can't push changes to the PR branch.
=> Apply #204

python_jsonschema_objects/__init__.py
Fix issue: https://github.com/cwacek/python-jsonschema-objects/issues/223
=> Removed the module jsonschema.compat and use the six package instead

python_jsonschema_objects/__init__.py
Fixes an issue that cropped up with referencing.jsonschema>=0.32.0
=> bugfix: Update the way specifications are retrieved.

python_jsonschema_objects/wrapper_types.py, test/test_pytest.py
Also a bug fix to handle literals being passed in
=> tests: Add a test to validate expected behavior on #278

python_jsonschema_objects/classbuilder.py, python_jsonschema_objects/literals.py, python_jsonschema_objects/validators.py, test/test_229.py, test/test_default_values.py
=> feature: Add support for the const keyword.
